name: Build and Deploy

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "16"

      - run: npm install --global yarn
      - run: yarn install
      - run: yarn run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: mateus.canelhas.io
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "sa-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "./dist" # optional: defaults to entire repository

      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: "EEV8VEGEEAVOQ"
          PATHS: "/*"
          AWS_REGION: "sa-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
