name: NPM CI/CD

on:
  release:
    types: [ released ]
    branches: [ master ]

jobs:
  publish_prod:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'

      - run: npm install
      - run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
          SOURCE_DIR: 'public'      # optional: defaults to entire repository